In [ ]:
import pandas as pd
import numpy as np
import cv2 as cv
import os
import keras

## create labels of dataset

### get file names

In [2]:
path = "/home/agathe/Documents/Bishop's/Research/project/data/"
files = os.listdir(path)
filename_list = np.array(files)

print(filename_list.shape)

(24104,)


### parse file names to get label informations

In [ ]:
def parse(file):
    labels = file.split("_")
    if len(labels) != 4: return
    for i in range(3):
        if labels[i].isdigit():
            labels[i] = int(labels[i])
    return labels[0:3]

labels = np.array(list(map(parse, filename_list)))
print(labels)

[[ 1  1  0]
 [62  1  0]
 [65  1  0]
 ...
 [45  1  0]
 [26  1  1]
 [29  0  1]]


: 

## find face in image

### upload image

In [ ]:
def read_image(file):
    filepath = path + file
    img = cv.imread(filepath)
    return img

images = np.array(list(map(read_image, filename_list)))

Corrupt JPEG data: premature end of data segment
libpng warning: iCCP: known incorrect sRGB profile
Corrupt JPEG data: bad Huffman code


In [ ]:
print(images[0])
cv.imshow('', images[0])

None


error: OpenCV(4.9.0) /io/opencv/modules/highgui/src/window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


In [ ]:
face_cas = cv.CascadeClassifier(cv.data.haarcascades + "haarcascade_frontalface_alt.xml")

def detectDisplay(frame):
    # transform image frame
    gray = cv.cvtColor(frame, cv.COLOR_RGB2GRAY)
    gray = cv.equalizeHist(gray)

    # find faces
    faces = face_cas.detectMultiScale(gray)

    print(faces)

detectDisplay(images[0])

error: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
